GET http://localhost:3000/employees

###

GET http://localhost:3000/employees/5e95ebfa4e5cd21e1864f1d3

###

POST http://localhost:3000/employees
Content-Type: application/json

{
    "name":  "Grigori",
    "surname": "Futurama",
    "email": "dasman@gmail2.com",
    "password": "12332111",
    "task": "jhgfd"
}

###

DELETE http://localhost:3000/employees/5e87ad33bb9c400608c5bd81

###

PATCH http://localhost:3000/employees/5e95ee2c9f8ce431b86c7d61
Content-Type: application/json

{
    "task": "afla managerii" 
}

### 
GET http://localhost:3000/register
